/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/NewAccountController'),
  Session: () => import('#controllers/SessionController'),
}
