/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Register: () => import('#controllers/RegisterController'),
  Login: () => import('#controllers/LoginController'),
}
